
COMMIT;

CREATE TABLE USER
(
    ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR(30),
    PASSWORD VARCHAR(30)
);


CREATE TABLE FACTURE
(
    ID INTEGER PRIMARY KEY,
    ID_CLIENT INTEGER REFERENCES USER(ID),
    MONTANT FLOAT
);

CREATE TABLE ARTICLE_FACTURE
(
    ID_FACTURE INTEGER REFERENCES USER(ID),
    ID_ARTICLE INTEGER REFERENCES article(ID),
    QUANTITIE INTEGER
);

DROP TABLE ARTICLE_FACTURE;


INSERT INTO USER (USERNAME, PASSWORD) VALUES ('a', 'a');

#TRIGGER :


CREATE TRIGGER TRIGGER_USER
BEFORE INSERT ON USER
FOR EACH ROW
BEGIN
    DECLARE nombre_de_tuples INT;
    SELECT COUNT(*) INTO nombre_de_tuples FROM user;

    SET NEW.ID = nombre_de_tuples + 1;
END;

####

CREATE TRIGGER TRIGGER_FACTURE
BEFORE INSERT ON FACTURE
FOR EACH ROW
BEGIN
    DECLARE nombre_de_tuples INT;
    SELECT COUNT(*) INTO nombre_de_tuples FROM FACTURE;

    SET NEW.ID = nombre_de_tuples + 1;
END;


##

COMMIT;


SELECT * FROM ARTICLE_FACTURE;

SELECT * FROM USER WHERE USERNAME LIKE 'a';


DELETE FROM ARTICLE_FACTURE WHERE ARTICLE_FACTURE.ID_ARTICLE > -1;
